name: Deploy to GH Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clean install
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build:prod

    - name: Copy 404.html
      run: cp dist/cv/index.html dist/cv/404.html

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/cv
